analysis:
  similarity_threshold: 0.85
  manual_identity_mappings: {}
  branch_mapping_rules: {}
  exclude_paths: []

cache:
  directory: ./.test-gitflow-cache
  ttl_hours: 168

output:
  directory: ./test-reports
  formats: ["csv", "json"]
  anonymize_enabled: false

github:
  token: ${GITHUB_TOKEN}
  organization: ${GITHUB_ORG}

repositories: []

qualitative:
  enabled: false
  openrouter_api_key: ${OPENROUTER_API_KEY}
  model: "openai/gpt-3.5-turbo"
  max_tokens: 1000
  batch_size: 100
  cache_enabled: true